import { CrmDeal, CrmMessage } from "./crm-types";

export const MOCK_DEALS: CrmDeal[] = [
  {
    id: "deal-bala-spf15",
    title: "Bala - Rice Ceramide Lip SPF 15",
    buyerId: "buyer-bala",
    buyerName: "House of Seoul (Bala)",
    buyerCountry: "🇮🇳 India",
    supplierId: "supp-greencos",
    supplierName: "그린코스 (Greencos)",
    pmName: "이기욱 (Thomas)",
    stage: "po_confirmed",
    priority: "hot",
    buyerUnitPrice: 2.50,
    buyerTotalQty: 5000,
    buyerTotalValue: 12500, // $12,500
    supplierUnitPrice: 1500, // ₩1,500
    supplierTotalCost: 7500000, // ₩7,500,000 (~$5,550)
    shippingCostUsd: 450,
    grossProfitUsd: 6500,
    marginPct: 52.0,
    productSpec: {
      productType: "Lip Treatment",
      volumeMl: 10,
      containerType: "D19 Squeeze Tube",
      keyIngredients: ["Rice Ceramide", "SPF 15 Filters"],
      regulatoryNotes: "인도 전용 배송 — OTC 절차 미적용 확인 완료",
      sampleStatus: "approved",
    },
    inquiryDate: "2026-08-10",
    sampleSentDate: "2026-08-14",
    poDate: "2026-08-21",
    expectedCloseDate: "2026-09-30",
    updatedAt: "2026-08-21 14:30",
  },
  {
    id: "deal-div20-ghkcu",
    title: "Division Twenty - GHK-Cu Serum 30ml",
    buyerId: "buyer-div20",
    buyerName: "Division Twenty",
    buyerCountry: "🇺🇸 USA",
    supplierId: "supp-pfnature",
    supplierName: "피에프네이처",
    pmName: "송준하 (COO)",
    stage: "quoting",
    priority: "hot",
    buyerUnitPrice: 4.80,
    buyerTotalQty: 5000,
    buyerTotalValue: 24000,
    supplierUnitPrice: 2200,
    supplierTotalCost: 11000000,
    shippingCostUsd: 600,
    grossProfitUsd: 15250,
    marginPct: 63.5,
    productSpec: {
      productType: "Serum",
      volumeMl: 30,
      containerType: "Glass Dropper Bottle",
      keyIngredients: ["GHK-Cu Peptide 1%", "Hyaluronic Acid"],
      sampleStatus: "shipped",
    },
    inquiryDate: "2026-08-12",
    sampleSentDate: "2026-08-18",
    updatedAt: "2026-08-20 09:15",
  },
  {
    id: "deal-annie-handcream",
    title: "Annie Won - Spout Pouch Hand Cream",
    buyerId: "buyer-annie",
    buyerName: "Aulaite (Annie Won)",
    buyerCountry: "🇺🇸 USA",
    supplierId: "supp-greencos",
    supplierName: "그린코스",
    pmName: "김형선 (Hally)",
    stage: "sourcing",
    priority: "warm",
    buyerUnitPrice: 1.90,
    buyerTotalQty: 5000,
    buyerTotalValue: 9500,
    supplierUnitPrice: 1100,
    supplierTotalCost: 5500000,
    shippingCostUsd: 400,
    grossProfitUsd: 5000,
    marginPct: 52.6,
    productSpec: {
      productType: "Hand Cream",
      volumeMl: 50,
      containerType: "Spout Pouch with Keyring",
      keyIngredients: ["Shea Butter", "Ceramide NP"],
      regulatoryNotes: "스파우트 파우치 충진 설비 공장 수용 가능성 확인 필요",
      sampleStatus: "in_formulation",
    },
    inquiryDate: "2026-08-18",
    updatedAt: "2026-08-21 11:20",
  },
  {
    id: "deal-nixaliz-cloud",
    title: "Nixaliz Yodice - Cloud Cream 2 types",
    buyerId: "buyer-nixaliz",
    buyerName: "Cloud Skincare",
    buyerCountry: "🇺🇸 USA",
    supplierId: "supp-greencos",
    supplierName: "그린코스",
    pmName: "이기욱 (Thomas)",
    stage: "sampling",
    priority: "hot",
    buyerUnitPrice: 3.50,
    buyerTotalQty: 3000,
    buyerTotalValue: 10500,
    supplierUnitPrice: 1800,
    supplierTotalCost: 5400000,
    shippingCostUsd: 350,
    grossProfitUsd: 6150,
    marginPct: 58.5,
    productSpec: {
      productType: "Moisturizing Cream",
      volumeMl: 50,
      containerType: "Airless Pump Jar",
      keyIngredients: ["PDRN 0.5%", "Panthenol"],
      sampleStatus: "shipped",
    },
    inquiryDate: "2026-08-13",
    sampleSentDate: "2026-08-21",
    updatedAt: "2026-08-21 16:45",
  },
  {
    id: "deal-charity-perfume",
    title: "Charity - TJ Solid Perfume 15g",
    buyerId: "buyer-charity",
    buyerName: "TJ Perfumes (Charity)",
    buyerCountry: "🇰🇪 Kenya",
    supplierId: "supp-oxygen",
    supplierName: "옥시젠디벨롭먼트",
    pmName: "박준영 (CEO)",
    stage: "sampling",
    priority: "warm",
    buyerUnitPrice: 2.80,
    buyerTotalQty: 3000,
    buyerTotalValue: 8400,
    supplierUnitPrice: 1400,
    supplierTotalCost: 4200000,
    shippingCostUsd: 500,
    grossProfitUsd: 4800,
    marginPct: 57.1,
    productSpec: {
      productType: "Solid Perfume",
      volumeMl: 15,
      containerType: "Metal Compact Balm Case",
      keyIngredients: ["Jojoba Wax", "Custom Fragrance Blend"],
      sampleStatus: "produced",
    },
    inquiryDate: "2026-08-08",
    sampleSentDate: "2026-08-21",
    updatedAt: "2026-08-21 15:10",
  },
  {
    id: "deal-hadjira-lipgloss",
    title: "Hadjira Elasri - Clear Lip Gloss 3-pack",
    buyerId: "buyer-hadjira",
    buyerName: "JIJII Beauty",
    buyerCountry: "🇩🇿 Algeria",
    pmName: "이기욱 (Thomas)",
    stage: "inquiry",
    priority: "warm",
    buyerUnitPrice: 0,
    buyerTotalQty: 5000,
    buyerTotalValue: 0,
    supplierUnitPrice: 0,
    supplierTotalCost: 0,
    shippingCostUsd: 0,
    grossProfitUsd: 0,
    marginPct: 0,
    productSpec: {
      productType: "Lip Gloss",
      volumeMl: 8,
      containerType: "Clear Wand Applicator Tube",
      keyIngredients: ["Hyaluronic Spheres", "Jojoba Oil"],
      sampleStatus: "not_started",
    },
    inquiryDate: "2026-08-21",
    updatedAt: "2026-08-21 18:00",
  },
];

export const MOCK_MESSAGES: Record<string, CrmMessage[]> = {
  "deal-bala-spf15": [
    {
      id: "m1",
      dealId: "deal-bala-spf15",
      senderType: "buyer",
      senderName: "Bala S. Pinnamaneni",
      senderEmail: "balupinnamaneni@gmail.com",
      content: "Hi Thomas, we confirmed the 10ml D19 squeeze tube packaging specs. Please prepare the 1st sample batch and send us the shipping timeline to Hyderabad.",
      timestamp: "2026-08-11 02:30",
    },
    {
      id: "m2",
      dealId: "deal-bala-spf15",
      senderType: "pm",
      senderName: "이기욱 (Thomas)",
      content: "Hi Bala, received! We matched your formulation with Greencos factory. Free samples (5 units) will be produced and shipped via DHL within 7 business days.",
      timestamp: "2026-08-11 09:15",
    },
    {
      id: "m3",
      dealId: "deal-bala-spf15",
      senderType: "supplier",
      senderName: "양우덕 PM (그린코스)",
      content: "기욱 PM님, 립 SPF 15 10ml 튜브 내용물 샘플 준비 완료되었습니다. DHL 발송용 파우치 패킹 마쳤습니다.",
      timestamp: "2026-08-14 14:00",
      aiSummary: "그린코스 샘플 제조 완료 및 배송 준비 보고",
    },
    {
      id: "m4",
      dealId: "deal-bala-spf15",
      senderType: "buyer",
      senderName: "Bala S. Pinnamaneni",
      senderEmail: "balupinnamaneni@gmail.com",
      content: "Great news. We also accept the direct assignment agreement with Medidakos & Greencos. What is the DHL tracking number once dispatched?",
      timestamp: "2026-08-21 14:30",
      actionRequired: true,
      aiSummary: "계약 구조 수락 및 DHL 추적번호 요청 (회신 필요)",
    },
  ],
  "deal-div20-ghkcu": [
    {
      id: "m21",
      dealId: "deal-div20-ghkcu",
      senderType: "buyer",
      senderName: "Alex Turner",
      senderEmail: "alex@divisiontwenty.com",
      content: "Here is our target GHK-Cu 1% formulation file. Can you match this exactly at 5,000 MOQ?",
      timestamp: "2026-08-12 10:00",
    },
    {
      id: "m22",
      dealId: "deal-div20-ghkcu",
      senderType: "pm",
      senderName: "송준하 (COO)",
      content: "Alex, PF Nature factory verified the formulation. Quoted at $4.80/unit for 5,000 units. Official Quotation attached.",
      timestamp: "2026-08-18 16:30",
    },
    {
      id: "m23",
      dealId: "deal-div20-ghkcu",
      senderType: "system",
      senderName: "CRM System",
      content: "⚠️ Follow-up Alert: 4 days since Quotation sent without buyer reply.",
      timestamp: "2026-08-21 09:00",
      actionRequired: true,
    },
  ],
};
