import type { TopProduct } from "./types";

export const TOP_PRODUCTS: TopProduct[] = [
  {
    id: "prod-01",
    rank: 1,
    nameEn: "Dive-In Low Molecular Hyaluronic Serum",
    nameKo: "다이브인 저분자 히알루론산 세럼",
    volume: "100ml",
    image: "/products/prod-01.svg",
    category: "skincare",
  },
  {
    id: "prod-02",
    rank: 2,
    nameEn: "Ato Barrier 365 Cream",
    nameKo: "아토베리어365 크림",
    volume: "80ml",
    image: "/products/prod-02.svg",
    category: "skincare",
  },
  {
    id: "prod-03",
    rank: 3,
    nameEn: "Hyaluronic Soothing Cream",
    nameKo: "히알루로닉 수딩크림",
    volume: "80ml",
    image: "/products/prod-03.svg",
    category: "skincare",
  },
  {
    id: "prod-04",
    rank: 4,
    nameEn: "Mung Bean Low-pH Cleansing Foam",
    nameKo: "녹두 약산성 클렌징폼",
    volume: "200ml",
    image: "/products/prod-04.svg",
    category: "skincare",
  },
  {
    id: "prod-05",
    rank: 5,
    nameEn: "Aqua Oasis Toner",
    nameKo: "아쿠아 오아시스 토너",
    volume: "300ml",
    image: "/products/prod-05.svg",
    category: "skincare",
  },
  {
    id: "prod-06",
    rank: 6,
    nameEn: "PDRN Capsule 100 Serum",
    nameKo: "피디알엔 캡슐 100 세럼",
    volume: "50ml",
    image: "/products/prod-06.svg",
    category: "skincare",
  },
  {
    id: "prod-07",
    rank: 7,
    nameEn: "Real Hyaluronic Blue 100 Ampoule",
    nameKo: "리얼 히알루로닉 블루100앰플",
    volume: "50ml",
    image: "/products/prod-07.svg",
    category: "skincare",
  },
  {
    id: "prod-08",
    rank: 8,
    nameEn: "Dive-In Low Molecular Hyaluronic Toner",
    nameKo: "다이브인 저분자 히알루론산 토너",
    volume: "300ml",
    image: "/products/prod-08.svg",
    category: "skincare",
  },
  {
    id: "prod-09",
    rank: 9,
    nameEn: "Cool Disposable Modeling Cup Pack",
    nameKo: "쿨 일회용 모델링 컵팩",
    volume: "28g",
    image: "/products/prod-09.svg",
    category: "skincare",
  },
  {
    id: "prod-10",
    rank: 10,
    nameEn: "Aqua Squalane Moisture Cream",
    nameKo: "아쿠아 스쿠알란 수분크림",
    volume: "80ml",
    image: "/products/prod-10.svg",
    category: "skincare",
  },
];
