import type { TopProduct } from "./types";

export const TOP_PRODUCTS: TopProduct[] = [
  {
    id: "prod-01",
    rank: 1,
    nameEn: "Moeve Anucatin No-Sebum Hair Cream",
    nameKo: "모에브 아누카틴 노세범 헤어크림",
    volume: "30g",
    image: "/products/prod-01.png",
    category: "skincare",
  },
  {
    id: "prod-02",
    rank: 2,
    nameEn: "Round Lab Birch Moisture Sun Cream",
    nameKo: "라운드랩 자작나무 수분 선크림",
    volume: "50ml",
    image: "/products/prod-02.png",
    category: "skincare",
  },
  {
    id: "prod-03",
    rank: 3,
    nameEn: "Mediheal Essential Mask Madecassoside",
    nameKo: "메디힐 에센셜 마스크 마데카소사이드",
    volume: "",
    image: "/products/prod-03.png",
    category: "skincare",
  },
  {
    id: "prod-04",
    rank: 4,
    nameEn: "Zeroid Daily Sun Cream",
    nameKo: "제로이드 데일리 선크림",
    volume: "",
    image: "/products/prod-04.png",
    category: "skincare",
  },
  {
    id: "prod-05",
    rank: 5,
    nameEn: "Cicaplast Multi Repair Cream B5",
    nameKo: "시카플라스트 멀티 리페어 크림 B5",
    volume: "100ml",
    image: "/products/prod-05.png",
    category: "skincare",
  },
  {
    id: "prod-06",
    rank: 6,
    nameEn: "Balanceful Cica Control Serum",
    nameKo: "밸런스풀 시카 컨트롤 세럼",
    volume: "50ml",
    image: "/products/prod-06.png",
    category: "skincare",
  },
  {
    id: "prod-07",
    rank: 7,
    nameEn: "Ato Barrier 365 Cream",
    nameKo: "아토베리어365 크림",
    volume: "",
    image: "/products/prod-07.png",
    category: "skincare",
  },
  {
    id: "prod-08",
    rank: 8,
    nameEn: "PDRN Capsule 100 Serum",
    nameKo: "피디알엔 캡슐 100 세럼",
    volume: "50ml",
    image: "/products/prod-08.png",
    category: "skincare",
  },
  {
    id: "prod-09",
    rank: 9,
    nameEn: "Dasima Ampoule Cleansing Foam",
    nameKo: "다시마 앰플 클렌징폼",
    volume: "",
    image: "/products/prod-09.png",
    category: "skincare",
  },
  {
    id: "prod-10",
    rank: 10,
    nameEn: "Daily Facial Cream",
    nameKo: "데일리 페이셜 크림",
    volume: "250ml",
    image: "/products/prod-10.png",
    category: "skincare",
  },
];